import turtle
import random as r
a = input("1匹目の線の色は？→")
b = input("1匹目の塗の色は？→")
c = input("2匹目の線の色は？→")
d = input("2匹目の塗の色は？→")
kame = turtle.Turtle()
kame.shape("turtle")
kame.shapesize(2,2,3)
kame.color(a,b)
kame.goto(-100,150) 
kame2 = turtle.Turtle()
kame2.shape("turtle")
kame2.shapesize(2,2,3)
kame2.color(c,d)
kame2.goto(-100,-150)
for i in range(5):
     mae = r.randint(10,100)
     print(mae)
     kame.fd(mae)
     mae = r.randint(10,100)
     print(mae)
     kame2.fd(mae)
turtle.done()